import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Wong Lab | UCLA',
  description: 'Generated by create next app',
}


function Nav() {
  return (
    <nav className='h-12 flex justify-between items-center'>
      <div>
        {/* Logo */}
        <Link href="/">
          <span className='text'>Wong Lab</span>
        </Link>
      </div>
      <div className='space-x-4'>
        <Link href="research">
          <span className='text'>Our Science</span>
        </Link>
        <Link href="members">
          <span className='text'>Members</span>
        </Link>
        <Link href="publications">
          <span className='text'>Publications</span>
        </Link>
      </div>
    </nav>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container xl:mx-auto`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
